In [1]:
import numpy as np

In [7]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista) # para declarar 

print(type(lista))
print(type(array))

print(lista)
print(array)

array[0] = 9
print(array)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
[9 2 3 4 5 6]


In [5]:
arr_zeros = np.zeros(10) # adiciona 10 zeros em uma array

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
## MATRIZES 

matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
## NOTAS DE ALUNOS

notas_alunos = []

for i in range(0, 5):
    notas = float(input(f'Informe a nota {i+1}:'))
    notas_alunos.append(notas)

print(notas_alunos)

notas = np.array(notas_alunos)

print(notas)

print(f'A maior nota: {notas.max()}') # max -> maior
print(f'A menor nota: {notas.min()}') # min -> minimo
print(f'A media das notas: {notas.mean():.2f}') # mean -> media

print(f'O desvio padrão das notas: {notas.std():.2f}') # std -> desvio padrão

print(f'A posição maior das notas: {notas.argmax()}') # argmax -> psição do maior
print(f'A posição menor das notas: {notas.argmin()}') # argmin -> psição do menor


Informe a nota 1: 10
Informe a nota 2: 3.5
Informe a nota 3: 7.6
Informe a nota 4: 4.5
Informe a nota 5: 9.5


[10.0, 3.5, 7.6, 4.5, 9.5]
[10.   3.5  7.6  4.5  9.5]
A maior nota: 10.0
A menor nota: 3.5
A media das notas: 7.02
O desvio padrão das notas: 2.61
A posição maior das notas: 0
A posição menor das notas: 1


In [34]:
!pip show notebook

Name: notebook
Version: 7.2.0
Summary: Jupyter Notebook - A web-based notebook environment for interactive computing
Home-page: 
Author: 
Author-email: Jupyter Development Team <jupyter@googlegroups.com>
License: BSD 3-Clause License

- Copyright (c) 2001-2015, IPython Development Team
- Copyright (c) 2015-, Jupyter Development Team

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software