In [1]:
import numpy as np

In [7]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista) # para declarar 

print(type(lista))
print(type(array))

print(lista)
print(array)

array[0] = 9
print(array)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
[9 2 3 4 5 6]


In [5]:
arr_zeros = np.zeros(10) # adiciona 10 zeros em uma array

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
## MATRIZES 

matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
## NOTAS DE ALUNOS

notas_alunos = []

for i in range(0, 5):
    notas = float(input(f'Informe a nota {i+1}:'))
    notas_alunos.append(notas)

print(notas_alunos)

notas = np.array(notas_alunos)

print(notas)

print(f'A maior nota: {notas.max()}') # max -> maior
print(f'A menor nota: {notas.min()}') # min -> minimo
print(f'A media das notas: {notas.mean():.2f}') # mean -> media

print(f'O desvio padrão das notas: {notas.std():.2f}') # std -> desvio padrão

print(f'A posição maior das notas: {notas.argmax()}') # argmax -> psição do maior
print(f'A posição menor das notas: {notas.argmin()}') # argmin -> psição do menor


Informe a nota 1: 10
Informe a nota 2: 3.5
Informe a nota 3: 7.6
Informe a nota 4: 4.5
Informe a nota 5: 9.5


[10.0, 3.5, 7.6, 4.5, 9.5]
[10.   3.5  7.6  4.5  9.5]
A maior nota: 10.0
A menor nota: 3.5
A media das notas: 7.02
O desvio padrão das notas: 2.61
A posição maior das notas: 0
A posição menor das notas: 1
